var https = require('https');
var fs = require('fs');
var crypto = require('crypto');
var pKey  = fs.readFileSync('./cert/key.pem', 'utf8');
var certificate = fs.readFileSync('./cert/cert.pem', 'utf8');
var credentials = {key: pKey, cert: certificate};
var path = require("path");
var sharedsession = require("express-socket.io-session");
var bodyParser = require('body-parser');
var crypto_tools = require('./crypto_tools');
var xor = require("buffer-xor");
var pg = require('pg');
var randomstring = require("randomstring");
var Buffer = require('buffer').Buffer;
var conString = "postgres://messenger:Mf5Bc54VC4BV54V7ws@localhost:5432/messenger";
var userSockets = {};       //сокеты, индексированные по ОКп
var userSocketCounter = 0;
var audSockets = {};        //сокеты ДУП индексированные по ОКдуп
var socketKeys = {};        //ключи шифрования сокетных соединений индексированные по именам сокетов
var plain = null;                  //флаг плейнтекста